### ISSUE TITLE
Spoof Google App using Lsposed

### ISSUE THREAD

**Issue by bhattom756** [fillwithjoy1/circle-to-search#1]
Hey, I install Lsposed, but there's no further info on how to  spoof my google app to pixel 8. Also where to flash the circle to search module, in magisk or Lsposed?

**Comment by fillwithjoy1** [comment]
1. Grab the release ZIP and flash that in Magisk. That's a magisk module you need to flash.
2. You'll need something that spoofs your device to Pixel 8. I have a LSPosed app over in github.com/fillwithjoy1/circle-to-search-spoofer that does that. 
3. Reboot
4. Go to Settings > Display > Gesture Navigation > Hold handle to search

tl:dr i need to improve the guide

**Comment by fillwithjoy1** [comment]
@Debug-001 I've just updated the Guide, see if that helps you

**Comment by bhattom756** [comment]
On the spoofer route, it says not found. Please check

**Comment by fillwithjoy1** [comment]
> On the spoofer route, it says not found. Please check

Send screenshots of the issue

**Comment by fillwithjoy1** [comment]
@Debug-001 I'm still waiting for your response. I'll close this issue if I haven't got the response

**Comment by fillwithjoy1** [comment]
No info. Closing issue
