### ISSUE TITLE
Not working on Samsung F23

### ISSUE THREAD

**Issue by Jass6969** [fillwithjoy1/circle-to-search#11]
My device is samsung f23. When i hold the search bar it shows gemini or google assistant. I even get the circle to search enable dialog in google app. But still when i hold the navigation bar it doesnt work plssss help

**Comment by fillwithjoy1** [comment]
> My device is samsung f23. When i hold the search bar it shows gemini or google assistant. I even get the circle to search enable dialog in google app. But still when i hold the navigation bar it doesnt work plssss help

Not sure about this one. Try spoofing as a Galaxy S23/S24 Ultra.

**Comment by Jass6969** [comment]
It still doesnt work video link
https://drive.google.com/file/d/1EU74K_eBpFxTph5tduHoNxoIPTJwXpAN/view?usp=drivesdk

**Comment by fillwithjoy1** [comment]
> It still doesnt work video link https://drive.google.com/file/d/1EU74K_eBpFxTph5tduHoNxoIPTJwXpAN/view?usp=drivesdk

Turn on gesture navigation and check

**Comment by Jass6969** [comment]
It still doesnt work
https://drive.google.com/file/d/1FambYtGlg9Zjbg4jz7sNfBy7GVKH_js4/view?usp=drivesdk

**Comment by fillwithjoy1** [comment]
> It still doesnt work https://drive.google.com/file/d/1FambYtGlg9Zjbg4jz7sNfBy7GVKH_js4/view?usp=drivesdk

Don't know then.
