### ISSUE TITLE
Assistant Voice Typing gets disabled

### ISSUE THREAD

**Issue by shailantani** [fillwithjoy1/circle-to-search#2]
Hi, so upon spoofing the pixel 8 configs and then flashing the zip,
I succesfully got the circle to search but the voice typing has greyed out options now
PS: It was working fine before spoofing the device.
Im running pixel 7a on Android 14 qpr 3 beta 2

![WhatsApp (2)](https://github.com/fillwithjoy1/circle-to-search/assets/98448265/03b2485d-1e92-4a98-9158-694402644127)

**Comment by shailantani** [comment]
Edit: the options came back. Everything works as usual. Thanks! ❤️

**Comment by fillwithjoy1** [comment]
Everything all good now? (please close the issue if everything is working as usual :))

**Comment by fillwithjoy1** [comment]
A note here: The Google app is responsible for the Google Assistant, so when you flash Pixel 8 props it forces the assistant to re-download all the files (I believe), so you'll need to be on Wi-Fi for that to download the relevant files.
