### ISSUE TITLE
Hold to handle option isn't showing in the settings 

### ISSUE THREAD

**Issue by doctor2oo2** [fillwithjoy1/circle-to-search#3]
I have done everything according to the instructions u hav given . But still the option isn't showing. Running pixel os a14 with stock pixel launcher. 
![Screenshot_20240626-200616](https://github.com/fillwithjoy1/circle-to-search/assets/83899631/c78ed8a8-18a1-46eb-abbb-acd840c45747)

**Comment by fillwithjoy1** [comment]
Do you have a pixel device? What's the current android build of it?

**Comment by doctor2oo2** [comment]
No its a xaoimi device 11T currently running android 14 on pixel os

**Comment by fillwithjoy1** [comment]
That's your problem right there. You aren't using a Pixel device

**Comment by fillwithjoy1** [comment]
In light of my previous comment being a bit harsh, my recommendation to you is to ask your ROM developer to implement it.
