### ISSUE TITLE
'Hold Handle to Search' NOT showing up in the Settings app

### ISSUE THREAD

**Issue by fufu2022** [fillwithjoy1/circle-to-search#5]
First greetings with regards to this niiiice work :)

Yet I failed to get the CTS functioning after carefully followed the stepes provided. 

There's no 'Hold Handle to Search' or 'Hold to invoke search' in the Gesture Settings page. (See the pic below)

![Screenshot_20240927-211342](https://github.com/user-attachments/assets/53e759b0-78da-4983-836a-b6b76753981b) 

Pls help if you may, with thanks & regards ahead.

More information if may help: I was able to use this function 'as it was', or 'out of the box' in the previous version of the ROM I'm currently using, but the more recent one not so I come here for it. 

I cannot find any activities related to 'hold to search ' or 'circle to search' thru those 'shortcut maker' apps in the ROM I'm currently using.

I'm not using a Pixel phone, and the ROM is PixelOS Android 14 AP2A.240905.

**Comment by fillwithjoy1** [comment]
I presume you fixed it same day?
