### ISSUE TITLE
The circle to search does not work

### ISSUE THREAD

**Issue by DarkNightcore8** [fillwithjoy1/circle-to-search#6]
I try to start it and, despite the fact that the phone seems to be camouflaged in a pixel 8 pro and the function activated, nothing appears if I hold down the bar. Does anyone know how to solve it? (Crdroid motorola g32 with android 14)

https://github.com/user-attachments/assets/d2a58476-8b61-4c3d-a463-248d33b97bee

**Comment by fillwithjoy1** [comment]
Launcher issue. Ask your ROM developer about this.
